"""shop settings and demo flag

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 08:16:53.735707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Демо-товары из первой версии сид-скрипта (индекс, название, число фото): помечаем их
# как демо и меняем фото-заглушки с placehold.co на картинки из assets/.
DEMO_PRODUCTS = [
    (0, 'Футболка оверсайз базовая', 3),
    (1, 'Футболка с принтом «Город»', 2),
    (2, 'Лонгслив в рубчик', 3),
    (3, 'Поло классическое', 3),
    (4, 'Спортивная футболка Dry-Fit', 2),
    (5, 'Худи оверсайз на флисе', 3),
    (6, 'Худи на молнии', 2),
    (7, 'Свитшот базовый', 3),
    (8, 'Укороченное худи', 3),
    (9, 'Джинсы прямые', 2),
    (10, 'Джинсы mom', 2),
    (11, 'Брюки классические', 2),
    (12, 'Брюки карго', 3),
    (13, 'Джоггеры спортивные', 2),
    (14, 'Куртка-бомбер', 2),
    (15, 'Пуховик укороченный', 2),
    (16, 'Ветровка', 2),
    (17, 'Тренч классический', 1),
    (18, 'Кеды белые кожаные', 1),
    (19, 'Кроссовки беговые', 2),
    (20, 'Ботинки челси', 2),
    (21, 'Лоферы', 2),
    (22, 'Кепка бейсболка', 3),
    (23, 'Шапка бини', 3),
    (24, 'Рюкзак городской', 2),
]


def _migrate_demo_photos() -> None:
    bind = op.get_bind()
    for index, title, photos in DEMO_PRODUCTS:
        ids = [
            row[0]
            for row in bind.execute(
                sa.text(
                    "SELECT DISTINCT p.id FROM products p JOIN product_photos ph "
                    "ON ph.product_id = p.id WHERE p.title = :title "
                    "AND ph.url LIKE 'https://placehold.co/%'"
                ),
                {"title": title},
            )
        ]
        for product_id in ids:
            bind.execute(
                sa.text("UPDATE products SET is_demo = :demo WHERE id = :id"),
                {"demo": True, "id": product_id},
            )
            bind.execute(
                sa.text("DELETE FROM product_photos WHERE product_id = :id"),
                {"id": product_id},
            )
            for n in range(photos):
                bind.execute(
                    sa.text(
                        "INSERT INTO product_photos (product_id, url, sort) "
                        "VALUES (:id, :url, :sort)"
                    ),
                    {"id": product_id, "url": f"asset:products/{index:02d}-{n}.png", "sort": n},
                )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_shop_settings'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###
    _migrate_demo_photos()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_demo')

    op.drop_table('shop_settings')
    # ### end Alembic commands ###
